### PR TITLE
feat: added home page

### PR DESCRIPTION
**Pull request by VishnuVNairCodes**
Preview: https://deploy-preview-1--kupaaya.netlify.app/

### CODE REVIEW

**Comment by smkmallik** [comment]
The code changes seems to be fine. I hope you can refactor the CSS code a bit more in future.  Some of the css properties has been declared directly. Home page is looking good for desktop view, later you can optimise the view for responsive screens.

It is okay to merge now. 😊

**Comment by VishnuVNairCodes** [comment]
> The code changes seems to be fine. I hope you can refactor the CSS code a bit more in future. Some of the css properties has been declared directly. Home page is looking good for desktop view, later you can optimise the view for responsive screens.
> 
> It is okay to merge now. 😊

Thank you for the feedback Soumik. I will surely look into it.

**Comment by AswathyVNair** [comment]
Looks great. 
UI Suggestion: The font-family used in button and search input are different from that of page's font-family. It would look much better if you could stick on one font-family.

**Review by AswathyVNair — APPROVED** [review]

**Comment by VishnuVNairCodes** [comment]
> Looks great. UI Suggestion: The font-family used in button and search input are different from that of page's font-family. It would look much better if you could stick on one font-family.

Thank you for pointing that out. I actually forgot to add font-family. The second font family in buttons etc is coming from the component library.

**Pull request merged**
